delete volume placeholder when error
chrislusf/seaweedfs pull request #1685
Opened 2020-12-17 10:44 UTC by qieqieplus

Delete placeholder from volumes when NewVolume()  failed

Also fix:
[store.go#L259](weed/storage/store.go#L259)

```
	found, err := location.deleteVolumeById(vid)
	if found {
		if err == nil {
			glog.V(0).Infof("volume %d is deleted", vid)
		} else {
			glog.V(0).Infof("delete volume %d: %v", vid, err)
		}
	}
```

won't log err, since `found` is always false when `deleteVolumeById` returns an error

2020-12-17 20:45 UTC, chrislusf requested changes
Related to https://github.com/chrislusf/seaweedfs/pull/1683

These two fixes are not needed. Need to find the original problem and prevent one volume being loaded twice.

2020-12-17 20:45 UTC, chrislusf commented on weed/storage/disk_location.go
> +		if v != nil {
Why put nil in the map in the previous PR?

2020-12-17 20:45 UTC, closed without merging

2020-12-18 03:23 UTC, qieqieplus commented on weed/storage/disk_location.go
> +		if v != nil {
explained in #1683

2020-12-18 03:29 UTC, qieqieplus commented
Still the other issue I mentioned in this pull request comment has not been addressed.

2020-12-18 03:38 UTC, chrislusf commented
Added a fix. How is it now?

2020-12-18 03:42 UTC, qieqieplus commented
LGTM

2020-12-18 03:43 UTC, chrislusf commented
Thanks!